### ISSUE TITLE
selections stomp over npm intellisense extension

### ISSUE THREAD

**Issue by ericblade** [zxqfl/tabnine-vscode#1]
It becomes quite difficult to use require() in node projects, as npm intellisense is getting completely stomped on by tabnine.

**Comment by zxqfl** [comment]
Would you be happy with an option to globally reduce TabNine priority in all files matching a certain glob, or is your issue limited to certain contexts such as require()?

**Comment by ericblade** [comment]
I don't really know how the whole system works, and it might be possible that they just aren't compatible with each other, but specifically when I do require('../../someFile'), sometimes in the middle of typing it out, the results from TabNine are mixed in with the npm-intellisense, sometimes they are the only thing in the list, and there are no results from npm-intellisense.   I'd prefer that the npm modules are on top of the list, versus apparently randomly ordered, or not even there. :-D

**Comment by ericblade** [comment]
so, i noticed it when i went to change a require('../constants') into a require('../../constants') .. after the first '..', i got mixed input, i hit the first /, and i got only suggestions from TabNine, which would be a great list, except it was a list of other requires, and not requires that are actually in the '../' directory. after the second '../', it gave me again a list mixed with TabNine and npm-intellisense results.  So, in the middle, I couldn't see anything from intellisense.

**Comment by zxqfl** [comment]
I don't really understand Intellisense's rules either. But I added some settings that will hopefully help. Specifically the "disable_line_regex" setting might be useful:

>  Disable TabNine when the current line contains a match of any of the provided regexes. For example, add "require" to disable TabNine when the current line contains the word 'require'.
