### ISSUE TITLE
Tooltip cuts off

### ISSUE THREAD

**Issue by International** [zxqfl/tabnine-vscode#11]
Hello,

When using the vscode version of the tool, it's not possible to read the entire autocomplete suggestion, and it's also not possible to scroll it. 

How should such cases be handled?
Thanks!

**Comment by zxqfl** [comment]
Unfortunately, we can't change the window size because it's managed by VS Code, not TabNine. We could trim TabNine's suggestions but I think this would remove some useful suggestions.
