### ISSUE TITLE
Multi-cursor support

### ISSUE THREAD

**Issue by nblackburn** [zxqfl/tabnine-vscode#12]
At the moment when are presented with suggestions, upon selecting one, only the first selection is populated. It would be nice if all selections were populated in the cases where you are using multiple cursors.

**Comment by ciaoben** [comment]
+1

![tabnine bug](https://user-images.githubusercontent.com/4526061/49992753-39c8e300-ff85-11e8-841d-1f0d70ab6040.gif)
