### ISSUE TITLE
suggestions are messed up

### ISSUE THREAD

**Issue by jabbalaci** [zxqfl/tabnine-vscode#15]
I noticed this problem some days ago, before that it worked well. Say I have a variable call "distance". If I type the beginning of it, "di", Tabnine suggests "distance". If I hit Enter on it, the result becomes "**di**distance", so I need to jump back and correct it manually.

**Comment by zxqfl** [comment]
Sorry about that, I'll try to get this fixed ASAP. What version of VS Code and what OS are you running?

**Comment by jabbalaci** [comment]
It doesn't happen all the time though, just rarely. Now I tried again and couldn't reproduce it in 5 minutes. It's a mysterious thing. 
VSCode: 1.29.1, x64
OS: Manjaro Linux

**Comment by zxqfl** [comment]
Darn. The completion mechanism was changed around a week ago, so that probably caused it. But the changes were necessary to support bracket pairing (where if the suggestion contains a `(` then a `)` is added after the cursor).

Let me know if you notice a pattern in when this occurs.

**Comment by jabbalaci** [comment]
Thanks for the quick reply. Yes, it appeared around a week ago. I will keep an eye on it and let you know.

**Comment by jabbalaci** [comment]
I can't recognize a pattern but I caught a case on video: https://www.dropbox.com/s/wvpeso1cnj0573c/tabnine.mp4?dl=0 . Here, "parseInt" is inserted by Tabnine as "**p**parseInt" after an Enter.

**Comment by zxqfl** [comment]
Thanks. I was able to reproduce the bug by typing 2 characters at the same time and then pressing Tab. (The delay before pressing Tab doesn't matter, only the delay between the characters.) I'm working on a fix.

**Comment by zxqfl** [comment]
This should be fixed in 1.0.4. Thanks for the report, and let me know if it's not.

**Comment by jabbalaci** [comment]
Thanks for the fix. I've tested it for a few days and this problem hasn't come back.

**Comment by stuzenz** [comment]
Tabnine looks great, but can we look at re-opening this issue. I am having the same problem using version 1.1.0 of tabnine (on the nightly insiders version of VS code)

Typing
<img width="882" alt="Screen Shot 2019-04-07 at 9 51 46 PM" src="https://user-images.githubusercontent.com/4701809/55681907-42a05300-5980-11e9-9f60-5f9328989e7d.png">

After tab or enter
<img width="333" alt="Screen Shot 2019-04-07 at 9 54 32 PM" src="https://user-images.githubusercontent.com/4701809/55681917-4f24ab80-5980-11e9-8df8-b9f00405f168.png">
