### ISSUE TITLE
TabNine spawning hundreds of Python processes via pyls

### ISSUE THREAD

**Issue by gmstriga** [zxqfl/tabnine-vscode#16]
After maybe half an hour of using the v1.0.3 TabNine extension for Python editing, my process tree looks like this:

![image](https://user-images.githubusercontent.com/38641699/49693104-17276c00-fb38-11e8-85a6-c3beaef33c6f.png)

Right now there's about 300 processes total in there, but my highscore is 1000+ before I noticed. Almost all of them are children of pyls.

**Comment by zxqfl** [comment]
You could type `TabNine::no_sem` to disable semantic completion. Otherwise, there's not much to be done: TabNine spawns a `pyls` instance but doesn't control what `pyls` does.

**Comment by gmstriga** [comment]
Thanks, I wasn't sure if TabNine was doing something wrong with it or if pyls was the problem. I'll post this to the pyls issues.
