### ISSUE TITLE
Language server unexpectedly quit

### ISSUE THREAD

**Issue by Deekers** [zxqfl/tabnine-vscode#19]
OS X 10.14.1
VSCode 1.30.0
TabNine 1.0.4 
Platform IDE 1.6.0

When coding a notification that the language server has stopped appears.  Follow suggestion to do a restart and problem usually re-appears within a few minutes.  Not sure of any log files or further info m=needed to resolve, just let me know.

**Comment by mhtvsSFrpHdE** [comment]
I have similar problem, it's powershell ps1 files in vs code editor.  
The html and typescript sem works fine, is the two require executable full path  
in TabNine.toml. Once it's added, it can work without fail.  
But there is no example for powershell.

**Comment by zxqfl** [comment]
This generally indicates an issue with the language server. You can configure a custom language server using the instructions at https://tabnine.com/semantic.

**Comment by mhtvsSFrpHdE** [comment]
@zxqfl Yep. Sure the issue with language server. There is no powershell semantic config example and I didn't successfully config "Microsoft Powershell Language Server" to use with TabNine.

So still have to wait for a update or patch or guide...
