### ISSUE TITLE
Conflicts with vscode's own TS/JS intellisense

### ISSUE THREAD

**Issue by stackia** [zxqfl/tabnine-vscode#20]
Without TabNine:
![image](https://user-images.githubusercontent.com/5107241/50199829-070c5980-038e-11e9-89e3-408ba3725ccb.png)

With TabNine:
![image](https://user-images.githubusercontent.com/5107241/50199815-f2c85c80-038d-11e9-8c03-5db3e031dc57.png)
with TabNine enabled (+semantic completion with flow), vscode only give suggestions from TabNine. but I can manually trigger a list containing all suggestions with Control+space

Expected behavior:
The completion list should contain all suggestions from TabNine and other sources when typing on-the-fly.

**Comment by ewired** [comment]
Same thing is happening with me when editing Kotlin files using the Kotlin extension (it has other issues so I suspected it); also experiencing the same Ctrl+Space behavior, if I catch it before TabNine shows its suggestions. IIRC with other languages, including TypeScript, TabNine was not previously broken for me.

**Comment by slig** [comment]
I'm having the exact same issue and, as far as I can tell, it wasn't happening before.

**Comment by 2234839** [comment]
I'm having the exact same issue

**Comment by Don-Osipov** [comment]
This one issue alone makes the program unusable. Other than this it's fantastic, but this is a deal-breaker.

**Comment by Gameghostify** [comment]
I've found that when you keep deleting and re-typing part of the word (can just be a letter), the intellisense suggestions suddenly appear on top of the tabnine ones again. Weird.

**Comment by 2234839** [comment]
I wrote a plugin that basically solves this problem  https://marketplace.visualstudio.com/items?itemName=llej.suggest-plus

**Comment by zxqfl** [comment]
https://github.com/zxqfl/tabnine-vscode/commit/03d2f57c558d441bbac5b635ad97699be9efb2ea tries to fix this issue, please update to tabnine-vscode version 2.1.16 and reply to let me know whether it worked.

**Comment by stackia** [comment]
> [03d2f57](https://github.com/zxqfl/tabnine-vscode/commit/03d2f57c558d441bbac5b635ad97699be9efb2ea) tries to fix this issue, please update to tabnine-vscode version 2.1.16 and reply to let me know whether it worked.

it works like a charm! thanks for the long-awaited fix😀

**Comment by hariprasadiit** [comment]
@zxqfl  This is still an issue. That PR didn't fix the issue.

**Comment by zeyad-shaban** [comment]
>  tries to fix this issue, please update to tabnine-vscode version 2.1.16 and reply to let me know whether it worked.
It didn't :(

> I wrote a plugin that basically solves this problem https://marketplace.visualstudio.com/items?itemName=llej.suggest-plus
This works for me

**Comment by uriklar** [comment]
Hi, any update on this issue? I'm using v3.2.17 and still only getting tabnine suggestions and not Typescript suggestions for example

**Comment by linonetwo** [comment]
This should be reopened, it blocks usage.

**Comment by linonetwo** [comment]
I think we need a new issue.
