### ISSUE TITLE
coc.nvim source

### ISSUE THREAD

**Issue by flowchartsman** [zxqfl/tabnine-vscode#24]
It would be awesome to have TabNine integration with [coc.nvim](https://github.com/neoclide/coc.nvim), though I'm not familiar enough with TabNine to know how it would work. If it implements LSP it probably wouldn't be too much work.

**Comment by bfulop** [comment]
🎉
https://github.com/neoclide/coc-tabnine

**Comment by zxqfl** [comment]
Looks great, will add to tabnine.com shortly.
