### ISSUE TITLE
vscode  sem to enable  semantic completion for c/c++

### ISSUE THREAD

**Issue by vincezengqiang** [zxqfl/tabnine-vscode#26]
the completion backend is "cquery", which you will need to install manually.
 what is cqery?how to fix it?

**Comment by vincezengqiang** [comment]
i have install cquery manually, but the tip still show, how to fix it?

**Comment by zxqfl** [comment]
The tooltip shows when TabNine received an error running the `cquery` command. If you get the tooltip despite installing cquery, then probably TabNine can't find it. Please follow the steps in https://tabnine.com/semantic starting from "If it works in the terminal, but TabNine can't find it".
