### ISSUE TITLE
Missing typescript config from TabNineExample.toml

### ISSUE THREAD

**Issue by nokola** [zxqfl/tabnine-vscode#27]
Please add it to TabNineExample.toml, I had to figure it out manually.

[language.typescript]
command = "typescript-language-server"
args = ["--stdio"]

**Comment by nshen** [comment]
where is this  file?

**Comment by nokola** [comment]
%appdata%\TabNine\TabNineExample.toml on Windows
File was there after I installed TabNine in VS code.
![image](https://user-images.githubusercontent.com/6869225/61425670-83d3c780-a8cc-11e9-8a16-20822ba9ca90.png)

**Comment by zxqfl** [comment]
This has now been added (https://github.com/zxqfl/TabNine/blob/master/TabNine.toml)
