### ISSUE TITLE
Not working in macOS or Windows.

### ISSUE THREAD

**Issue by jiahao-shen** [zxqfl/tabnine-vscode#29]
After this plugin installed, nothing happened, no probability and no autocompletor

**Comment by kwiss** [comment]
did you pay ?

**Comment by jiahao-shen** [comment]
Isn't it for free?

**Comment by zxqfl** [comment]
The free version is supposed to work without paying. What version of VS Code are you running?

**Comment by jiahao-shen** [comment]
1.36.1

**Comment by jiahao-shen** [comment]
When i write c or cpp, it shows this.
<img width="384" alt="屏幕快照 2019-07-19 09 42 02" src="https://user-images.githubusercontent.com/29255648/61503372-2180e100-aa0a-11e9-82fc-37e7254e06dc.png">
iStat Menus shows that vscode in high load.
<img width="326" alt="屏幕快照 2019-07-19 09 42 21" src="https://user-images.githubusercontent.com/29255648/61503412-4412fa00-aa0a-11e9-88cc-06e487a95187.png">
And then the python, even has no percent.
<img width="952" alt="屏幕快照 2019-07-19 09 45 18" src="https://user-images.githubusercontent.com/29255648/61503427-53924300-aa0a-11e9-8928-26a74fa208f2.png">

**Comment by zxqfl** [comment]
Are you part of the beta, i.e. did you receive an invite and an API key?

**Comment by jiahao-shen** [comment]
Nope, isn't it public? It just for beta user now?

**Comment by zxqfl** [comment]
TabNine Cloud is in beta. See https://tabnine.com/blog/deep. It's working as intended; the CPU usage should stop once it's done indexing your project.
