### ISSUE TITLE
How do I disable it for SCSS?

### ISSUE THREAD

**Issue by usaphp** [zxqfl/tabnine-vscode#3]
I wish I can disable it in some file formats that I have other auto suggesters that I like more, especially in css.

**Comment by zxqfl** [comment]
There's a setting to disable TabNine when the filename matches a regex. Go to settings -> extensions -> TabNine.

**Comment by usaphp** [comment]
Thank you for your great work, purchased and am very happy using it :)

**Comment by zxqfl** [comment]
Glad to hear it :)
