### ISSUE TITLE
Not able to run tabnine in VS

### ISSUE THREAD

**Issue by DivyaWadehra** [zxqfl/tabnine-vscode#30]
Not getting TabNine messages, although the extension is installed

**Comment by 625781186** [comment]
me too.
![image](https://user-images.githubusercontent.com/30521429/61569625-d246b900-aaba-11e9-8de5-96a63e32ed99.png)

**Comment by ifree321** [comment]
What should I do? I have the same issue.

**Comment by colddie** [comment]
Same here. No response from tabNine::version.

**Comment by 625781186** [comment]
I think we confused `tabNine` with `deep tabNine`.
`tabNine` just record history input.
`deep tabNine` has cloud tip.

**Comment by elonliu** [comment]
In my case it worked yesterday but not today. 
By disabling and re-enabling and then reloading the plugin, it works again. Don't know why.

**Comment by zxqfl** [comment]
Can you clarify what you mean by 'not getting TabNine messages'? Does it mean that no suggestions from TabNine appear at all?

**Comment by ppnman** [comment]
> What should I do? I have the same issue.

You can restart vscode. It works for me.

**Comment by colddie** [comment]
> I think we confused `tabNine` with `deep tabNine`.
> `tabNine` just record history input.
> `deep tabNine` has cloud tip.

where to find that?

**Comment by Solido** [comment]
Idem the tabNine cmd for enable sem is not available but the plugin is installed

**Comment by zxqfl** [comment]
You should type it into the file you're editing, like in this video: https://update.tabnine.com/v/enable_cloud.mp4

**Comment by localjo** [comment]
I installed TabNine with `ext install TabNine.tabnine-vscode` and I have the same problem. No command palette options for TabNine are showing up. I noticed that version 1.1.0 is installed, but the email I got said 2.0.2 is the latest version. VS Code doesn't seem to see that version available anywhere. Screenshots from @625781186 are what I'm seeing too.

**Comment by zxqfl** [comment]
Hi localjo,

Version 1.1.0 is bundled with the VS Code plugin, but it should update automatically to 2.0.2. Can you try restarting your editor and typing TabNine::version? This should trigger an automatic update.

Note that commands need to be typed into the file you're editing, rather than typed into the command palette. Lots of users expect it to work in the command palette, so we hope to add it in the future.

**Comment by localjo** [comment]
I restarted VS code three times. No luck.

**Comment by zxqfl** [comment]
If you type TabNine::target, what does it display?

**Comment by localjo** [comment]
Nothing

**Comment by zxqfl** [comment]
And does the TabNine::version command work, or are you getting the version by looking at the extension directory?

**Comment by localjo** [comment]
![Screen Shot 2019-07-25 at 3 14 17 PM](https://user-images.githubusercontent.com/516388/61901914-e4778b80-aeee-11e9-9868-633dffb5faec.png)

**Comment by localjo** [comment]
No commands match anything starting with `TabNine`

**Comment by zxqfl** [comment]
Commands need to be typed into the file you're editing, rather than typed into the command palette.

**Comment by zxqfl** [comment]
See the gif in the beta invite email for an example

**Comment by localjo** [comment]
Ok. That works. It's a bit strange that the plugin doesn't use the command palette or the VS code settings panels. Feels a little bit sketchy to have to type commands directly into a file to access the plugin's settings and that the plugin just launches a new browser window which hijacks window focus when you type a certain string.

**Comment by zxqfl** [comment]
Okay, we'll take your feedback into account. The main advantage of this approach is that it doesn't require cooperation from the editor, which makes it easier especially for third-party plugin developers who don't have to implement custom logic.

**Comment by localjo** [comment]
Yes, but the user experience feels hacky and unsafe.

**Comment by zxqfl** [comment]
Can you elaborate on why it feels unsafe? Do you see a way in which it could compromise security?

**Comment by localjo** [comment]
It's just a feeling. A plugin that doesn't respect the norms of the VS code environment and launches a browser window without my explicit intention just because I typed `magic string` in the editor window comes across as hacky and unpredictable. I know it's a beta, but in this state, I wouldn't have this plugin installed while working on a real project.

**Comment by zxqfl** [comment]
Ok, we'll take your feedback into account and consider offering an alternate way of launching the config panel.

**Comment by ifree321** [comment]
Oh, it works, type the commands into the file. Thanks! @zxqfl https://update.tabnine.com/v/enable_cloud.mp4

**Comment by clonn** [comment]
In my opinion, this should be noted in the readme.

https://update.tabnine.com/v/enable_cloud.mp4

Most of VSCode user setup config via Control(Cmd) + shift + p, but config not in the file.

**Comment by r3nderer** [comment]
I have typed TabNine::version directly into the file I'm editing and nothing happens. I reinstalled the extension and restarted vscode, and still nothing.

**Comment by onionpsy** [comment]
@r3nderer I had the same issue but I fixed by creating a new file and inserting the command there. still a really weird way to access the config...

**Comment by rosstex** [comment]
Agree that it feels janky af. The extension itself is amazing though!

**Comment by Hraesvelgr12** [comment]
Hi, I just want to say that in my case it was necessary to activate the "Cloud" option and to do that is necessary to log in your Tabnine account in the VSCode>Tabnine settings , I don't know why but that function for me.
