### ISSUE TITLE
Not able to insert next suggestion using tab

### ISSUE THREAD

**Issue by d9yuan** [zxqfl/tabnine-vscode#31]
How can I insert next suggestion by pressing tab like in Sublime Text? I could cycle through all the suggestions using tab only in Sublime Text, but however I couldn't get it to work in VScode for TapNine. It works when other language autocompleter provides suggestions, but when there is only TapNine, when I first press tab it inserts the best suggestion, and tab again it won't insert the next suggestion but instead inserts '\t'. Is there a way to resolve this issue?

**Comment by zxqfl** [comment]
This is a nice suggestion, but the completion popup is managed by VS Code, so we can't implement this suggestion from within TabNine.
