### ISSUE TITLE
Occupying a lot of memory

### ISSUE THREAD

**Issue by yuuk** [zxqfl/tabnine-vscode#34]
![E44E38BC12051455531C54AAAD158313](https://user-images.githubusercontent.com/9426456/61943627-71dddd00-afce-11e9-9d89-4d9f52cef8c4.jpg)

**Comment by zxqfl** [comment]
This is normal, TabNine uses the memory to index your project

**Comment by ferrinweb** [comment]
1.4GB, 1.9GB sometimes memory used by TabNine.
![TIM截图20190902185137](https://user-images.githubusercontent.com/3353839/64110508-f5040700-cdb4-11e9-9f48-87a54a3cd37b.png)

**Comment by jiangtao** [comment]
how to limit the process amount。 It It consumes a lot of CPU
