### ISSUE TITLE
Wrong version installed (1.0.1)

### ISSUE THREAD

**Issue by AlessandroAnnini** [zxqfl/tabnine-vscode#36]
![image](https://user-images.githubusercontent.com/3852307/61967730-6393bf00-afd6-11e9-9a48-83f95e02e7c6.png)

`1.0.1` this is the only version i get.
using `ext install TabNine.tabnine-vscode` i get the same version.

**FORGET IT, IT WORKS, ONLY THE VERSION SHOWN IS WRONG**

**Comment by zxqfl** [comment]
Hi Alessandro. Can you try typing TabNine::version into your editor? You’re seeing the extension version, which is (confusingly) separate from the TabNine binary version.

**Comment by AlessandroAnnini** [comment]
Yes @zxqfl it works, I made a type on "version" :)

**Comment by AlessandroAnnini** [comment]
but you could specify that it won't work if you simply paste it, you just have to write it
