### ISSUE TITLE
TabNine::config does not open web browser

### ISSUE THREAD

**Issue by wangjess** [zxqfl/tabnine-vscode#37]
Here is a Gyazo of this behavior: https://gyazo.com/6ebe0c61c92592cbb2638e5fdc3045fb

Also, when I typed `TabNine::version` initially (not in that Gyazo), it showed version 1.0.1 in a little window.

**Comment by zxqfl** [comment]
It looks like you're using Atom, which is different from the other editors in that it needs a restart for the update to work. Can you try restarting the editor?

**Comment by ramenatorr** [comment]
I'm having the same issue, and I'm using VS Code 1.36.1 on macOS. I'm not quite sure what the expected action is after typing the TabNine::commands...

I am guessing it's as simple as hitting enter? Otherwise, I'm stumped.

**Comment by LemonAndroid** [comment]
I'm using vscode `Version 1.36.1 (1.36.1)` and for me it worked fine.

**Comment by LemonAndroid** [comment]
Just confirmed with @wangjess that she is using VSCode.

**Comment by ramenatorr** [comment]
> I'm using vscode `Version 1.36.1 (1.36.1)` and for me it worked fine.
> 
> Also on Mac OS X Mojave.

Were you just hitting Enter after typing up **TabNine::config**?

**Comment by wangjess** [comment]
Sorry am new to Github issues. I also typed `TabNine::config` and tried hitting Enter. Did not do anything.

**Comment by LemonAndroid** [comment]
@ramenatorr I didn't press any more buttons or click, it just opened the config page in the browser automagically.

**Comment by ramenatorr** [comment]
Okay @LemonAndroid , the automagic seems to be broken or not working for me and @wangjess .

If you can think of anything worth trying, I'm all ears.

**Comment by zxqfl** [comment]
I just upgraded the bundled binaries to version 2.0.2. Can you try upgrading your VS Code TabNine extension to 1.3.0 and seeing if this fixes the problem?

**Comment by wangjess** [comment]
How do I upgrade the extension in VS Code? I only see options to uninstall, install another version (and it only lists up to 1.1.0).

**Comment by zxqfl** [comment]
It sounds like the update hasn't fully propagated yet. Can you try again in a few minutes? Restarting VS Code might help too.

**Comment by wangjess** [comment]
It installed 1.3.0 and that fixed the problem! I just registered my activation key. Thanks for your help. Hopefully this works for @ramenatorr as well.

**Comment by cchamberlain** [comment]
Hitting similar using vscode remote extensions. I'm running from macos, trying to hit a Docker container on a debian based host (ssh through remote extensions).

I believe the issue might be that its attempting to navigate `127.0.0.1` which should be `0.0.0.0` in a container. Is there any way to adjust the host / port it uses?

**Comment by zxqfl** [comment]
Is the TabNine binary running on the remote host? If so you can try the instructions in https://tabnine.com/faq#browser_failed.

**Comment by cchamberlain** [comment]
Awesome, I had gotten it working locally ahead of time and saw that but missed the bit about copying over the config manually. After doing that it's working now. Thanks for the quick reply!

**Comment by ramenatorr** [comment]
Can confirm that this is working after the upgrade to 1.3.0

**Comment by Fahimsadnan** [comment]
april fool
