### ISSUE TITLE
Tabnine was unable to install javscript semantic completion

### ISSUE THREAD

**Issue by velteyn** [zxqfl/tabnine-vscode#38]
Hello, I installed tabnine on VSCODE right now using the instructions provided.
When I type TabNine::version I obtain a popup with the message I put on the file attach.

![immagine](https://user-images.githubusercontent.com/1019294/62031251-323e0d80-b1e7-11e9-982f-26ab32786916.png)

**Comment by velteyn** [comment]
Ok I managed to install it...

**Comment by liflovs** [comment]
@velteyn how did you get it to work?

**Comment by liflovs** [comment]
I`ve posted the same issue on another repo cause cannot install it

**Comment by velteyn** [comment]
Hi.
I followed this guide https://tabnine.com/semantic
Follow the link on the table about javascript. After I installed the server the error evaporated.
