### ISSUE TITLE
Does TabNine support vscode-cpptools as its C++ semantic completion backend?

### ISSUE THREAD

**Issue by hankbao** [zxqfl/tabnine-vscode#39]
Cquery is slow on my computer. It sometimes takes 100% cpu to index files and produces thousands of index files. So I wonder if I can switch the sem backend to Microsoft VSCode C++ Extension? Since it seems that vscode-cpptools also implements the LSP according to https://microsoft.github.io/language-server-protocol/implementors/servers/

**Comment by atyshka** [comment]
+1 on this. I know you can add language servers in the .config, I'm just not sure what the args needed for cpptools are

**Comment by zxqfl** [comment]
I recommend customizing the language server using the instructions at https://tabnine.com/semantic.
