### ISSUE TITLE
This would be a GREAT plugin for the JetBrains Suite

### ISSUE THREAD

**Issue by GenesisCraig** [zxqfl/tabnine-vscode#40]
Write the plug-in once and it would work across all their products (Java, Javascript, Python, PHP, C#, Go, etc...).  They have a lively ecosystem and good plugin "store".

**Comment by LemonAndroid** [comment]
How often do you use Jetbrains across all their projects? Percentage of daily use would be preferred.

**Comment by GenesisCraig** [comment]
Except for this week, where I'm using VSC just to use TabNine, I'm 90% in one JetBrains IDE or another.  I use their DataGrip for SQL/MySQL work, PHPstorm for PHP/Webdev, and PyCharm for my Python/GIS work.

They've got very high marketshare for Java, JavaScript/NodeJS, and Python.  Just a thought for you if you want to write a single plugin and possibly gain a whole new segment.

**Comment by zxqfl** [comment]
We've just released an IntelliJ plugin. It's pending official approval to be added to the JetBrains repository, but in the meantime you can get it at https://update.tabnine.com/intellij/TabNine-0.0.2.jar (install instructions at https://www.jetbrains.com/help/idea/managing-plugins.html#install_plugin_from_disk)

**Comment by zxqfl** [comment]
(should work for all JetBrains IDEs, let me know if it doesn't)
