### ISSUE TITLE
The popup window too long and can't view entire hint content

### ISSUE THREAD

**Issue by mhtvsSFrpHdE** [zxqfl/tabnine-vscode#46]
![image](https://user-images.githubusercontent.com/10773245/63010034-35f4b400-beb8-11e9-9a82-1899c99195a2.png)

The image shows how VSCode cut the too long hint content...  
Both Windows VSCode and Linux VSCode have this problem.  
TabNine 2.0.4  
VSCode 1.37.0

**Comment by zxqfl** [comment]
The completion popup is managed by VS Code and shared across completion extensions, so we unfortunately can't fix this issue from within TabNine.
