### ISSUE TITLE
wrong vscode install instructions?

### ISSUE THREAD

**Issue by komuw** [zxqfl/tabnine-vscode#5]
This page; https://tabnine.com/install says the install command for the extension in vscode is 
```sh
ext install TabNine.tabnine-vscode
```
I think it ought to be;
```sh
code --install-extension TabNine.tabnine-vscode
```

**Comment by cstuder** [comment]
The first one is a command within VSCode, press CTRL-P and then enter the `ext`-command to install it.

The second one is the command to install it from the CLI.

Both work, they are just used in a different spot.

**Comment by komuw** [comment]
thanks.
